env:
  browser: false
  es2021: true
  mocha: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
plugins:
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
rules:
  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
        - modules
